version: '3.9'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  mysql-data:
